# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 05:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='evento',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre del Evento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True, verbose_name='Celular +503 XXXXXXX'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Sector'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together=set([('persona', 'evento')]),
        ),
    ]
