# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_auto_20160320_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'verbose_name': 'Joven Asistencia', 'verbose_name_plural': 'Jovenes que Asisten los Eventos'},
        ),
    ]
