# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20160319_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Evento', verbose_name='Evento')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Persona', verbose_name='Persona que Asiste')),
            ],
            options={
                'verbose_name_plural': 'Asistencia a Eventos',
            },
        ),
    ]
